addon/components/freestyle-guide/component.js, addon/components/freestyle-guide/template.hbs, addon/components/freestyle-usage-controls/template.hbs, app/styles/components/freestyle-guide.scss, app/styles/components/freestyle-usage-controls.scss, app/styles/ember-freestyle.scss, bower.json, ember-cli-build.js, index.js, package.json
- Make it easier for a consuming app to get going
- Tolerate absent freestyle directory
- Proxy remarkable and highlight.js dependencies
TODO: Add a blueprint
=> Standardize dependencies

app/styles/components/freestyle-guide.scss, app/styles/components/freestyle-usage.scss, app/styles/ember-freestyle.scss, index.js, package.json, tests/dummy/app/styles/app.scss, tests/dummy/app/styles/breakpoints.scss, tests/dummy/app/styles/reset.scss
Resolves #21 https://github.com/chrislopresto/ember-freestyle/issues/21
=> Remove mappy-bp dependency

README.md, app/styles/ember-freestyle.scss, blueprints/ember-freestyle/files/app/styles/app.scss
...as overridable SCSS variables
Resolves https://github.com/chrislopresto/ember-freestyle/issues/27
=> Provide default Ember Freestyle color palette

addon/components/freestyle-subsection.js, addon/templates/components/freestyle-subsection.hbs, app/styles/components/freestyle-subsection.scss, app/styles/ember-freestyle.scss
Supersedes https://github.com/chrislopresto/ember-freestyle/pull/36
=> Add subsection header

README.md, addon/components/freestyle-collection.js, addon/components/freestyle-variant.js, app/styles/components/freestyle-collection.scss, app/styles/components/freestyle-variant.scss, app/styles/ember-freestyle.scss, tests/dummy/app/templates/application.hbs
Resolves https://github.com/chrislopresto/ember-freestyle/issues/53
=> Display freestyle-collection variants inline

README.md, ember-cli-build.js, index.js
Since this is a breaking change, we should look at https://github.com/chrislopresto/ember-freestyle/issues/48 to decide if we want to rename anything else in the process.
Resolves https://github.com/chrislopresto/ember-freestyle/issues/50
=> Scope freestyle options for safekeeping

addon/components/freestyle-usage.js, addon/templates/components/freestyle-usage.hbs, package.json, tests/acceptance/collection-navigation-test.js, tests/acceptance/collection-rendering-test.js, tests/acceptance/section-navigation-test.js, tests/acceptance/section-rendering-test.js, tests/integration/components/freestyle-usage/component-test.js, tests/pages/freestyle-guide.js, tests/pages/usage-component.js
@chrislopresto, per your comment, here are the testing changes squashed.
=> Add some better test coverage before refactoring.

addon/components/freestyle-snippet.js
This should probably have some tests.
=> Fix snippet language detection

package.json, yarn.lock
Update ember-cli-showdown and ember-cli-htmlbars dependencies.
=> Update ember-cli-showdown and ember-cli-htmlbars

.travis.yml, README.md, config/ember-try.js, package.json
=> Update documentation for ember 2.4

addon/components/freestyle-snippet.js, tests/dummy/app/templates/acceptance.hbs, tests/integration/components/freestyle-usage/component-test.js, tests/pages/usage-component.js
Fixes https://github.com/chrislopresto/ember-freestyle/issues/173
=> Don't include blank lines when determining how much to unindent

README.md
I don't think ember-freestyle has a dedicated channel in the Discord, so I just removed it.
=> Remove Slack and add Discord

addon/components/freestyle-dynamic.js, package.json, yarn.lock
NOTE: this is a placeholder commit that will be revised! It will be amended when aexmachina/ember-cli-sass#205 is merged and a release is cut with that change in place.
I'm opening this PR to allow my team to make progress via the fork in the meantime.
=> Update ember-cli-sass to use Dart Sass.

addon/components/freestyle-dynamic.js, addon/components/freestyle-snippet.js, addon/components/freestyle-usage.js, tests/unit/components/freestyle-dynamic/component-test.js
https://deprecations.emberjs.com/v3.x/#toc_computed-property-override
=> fix: Remove computed property override deprecation

addon/styles/components/freestyle-notes.scss, addon/templates/components/freestyle-showdown-content.hbs, tests/dummy/app/templates/acceptance.hbs, tests/dummy/app/templates/documentation.hbs
=> feat: Add support for markdown tables

.all-contributorsrc, README.md, package.json, yarn.lock
Add contributors to the README with https://allcontributors.org/
This PR adopts the [All Contributors spec](https://allcontributors.org/) and adds all contributors to the README.
=> docs: Adopt All Contributors

addon/components/freestyle/usage/argument/index.hbs
`hasBlock` is soon to be deprecated.
=> Switch to `has-block`

blueprints/ember-freestyle/files/__root__/app/templates/freestyle.hbs
Took me a while to figure out why my Freestyle instance is not rendering anything in the content area.
=> Fix subsection invocation

app/helpers/pick.js
More info: https://github.com/emberjs/ember.js/pull/19365
=> chore: remove pick helper named re-export

addon/components/freestyle-palette/index.hbs, addon/components/freestyle-palette/index.js, tests/integration/components/freestyle-palette/component-test.js
- Fixes rendering the color palette (doesn't render any colors at the moment)
- Fixes rendering the default title when the user does not provide one
- Renders a default description when the user does not provide one
=> fix: rendering a color palette

blueprints/ember-freestyle/index.js, config/deploy.js
This is already covered [here](https://github.com/chrislopresto/ember-freestyle/blob/master/.eslintrc.js#L45) and [here](https://github.com/chrislopresto/ember-freestyle/blob/master/.eslintrc.js#L46).
=> Remove unneeded ESLint comments

package.json, yarn.lock
Could be wrong, but this doesn't seem to be needed anymore?
=> Remove `ember-cli-shims`

package.json, yarn.lock
Doesn't seem to be needed anymore.
=> Remove `ember-runtime-enumerable-includes-polyfill`

addon/components/freestyle-dynamic-input/index.js
`elementId` is `null` for components with `tagName: ''`.
=> Fix generated id for `freestyle-dynamic-input` component

addon/components/freestyle-section/index.js, addon/components/freestyle-subsection/index.js, lib/ast-transform.js
As there were actually no violations.
=> Remove unneeded `eslint-disable` comments

.npmignore
=> Don't publish husky folder

README.md, tests/dummy/app/templates/documentation.hbs
=> Recommend `exclude` option instead of `blacklist` option

addon/components/freestyle-dynamic-input-select-option/index.ts, addon/components/freestyle-dynamic-input/index.ts, addon/components/freestyle-focus-button/index.ts, addon/components/freestyle-palette-item/index.ts, addon/components/freestyle-typeface/index.ts, addon/components/freestyle-usage-controls/index.ts, addon/components/freestyle-variant-list/index.ts, addon/components/freestyle/usage/number/index.ts, addon/components/freestyle/usage/object/index.ts, addon/components/freestyle/usage/string/index.ts, addon/modifiers/freestyle-highlight.ts, tests/dummy/app/components/progress-icon/index.ts
=> Remove use of private `EmptyObject` type

app/styles/components/freestyle-menu.scss, app/styles/components/freestyle-section.scss, app/styles/components/freestyle-subsection.scss, vendor/ember-freestyle.css
=> Eliminate uppercase'ing of menu items and update menu item hover state

.github/workflows/ci.yml, README.md, package.json
=> Drop support for Node versions below v18
