chrislopresto/ember-freestyle

freestyle-usage-snippet-finder.js, index.js
Resolves https://github.com/chrislopresto/ember-freestyle/issues/11
=> Warn if duplicate slugs are detected

.sass-lint.yml, addon/components/freestyle-section.js, addon/components/freestyle-usage.js, addon/templates/components/freestyle-usage.hbs, app/styles/components/freestyle-palette-item.scss, app/styles/components/freestyle-section.scss
Support the following snippet in SCSS:
```scss
/* BEGIN-FREESTYLE-USAGE modules-buttons-normal:notes
Use these whenever you need some kind of clickable surface to afford an action that
isn't a boring, inconspicuous text link.
END-FREESTYLE-USAGE */
```
=> Support SCSS Note Snippets

addon/templates/components/freestyle-usage.hbs, app/styles/components/freestyle-palette-item.scss
=> Move rendered component next to its corresponding code snippet

index.js
This should always be false for releases. Otherwise the files in the addon are linted alongside the
consuming applications codebase. And possibly other side-effects as well...
=> Return false for `isDevelopingAddon`

addon/templates/components/freestyle-usage-controls.hbs, app/styles/components/freestyle-guide.scss, app/styles/components/freestyle-palette-item.scss, app/styles/components/freestyle-section.scss, app/styles/components/freestyle-usage-controls.scss, app/styles/components/freestyle-usage.scss, app/styles/ember-freestyle.scss, blueprints/ember-freestyle/files/__root__/app/templates/freestyle.hbs, package.json
- Fixes color contrast issues with the default colors used in the stylesheets (found using ember-a11y-testing)
- Replaced div with labels
- Added enter action to focus input
- Fixed indentation in the blueprints to be compliant with ember-cli-template-lint
- Make all color variables in stylesheets overridable
=> a11y & template linting fixes

addon/components/freestyle-collection.js, package.json
=> Use `includes` instead of `contains`, which is deprecated in ember 2.8+

package.json
This kills [npm package published with engine: "ember-cli-app-version"](https://github.com/jmurphyau/ember-truth-helpers/issues/46).
=> Update ember-truth-helpers to 1.3.0

addon/templates/components/freestyle-menu.hbs
@chrislopresto First of all this addon is amazing!
The PR fixes a minor bug. You can see it in action:
http://chrislopresto.github.io/ember-freestyle/?f=foo-normal&s=Foo%20Things&ss=Foo%20Subsection%20A
If you click on an item in the navigation a blank page is rendered. The PR fixes it by reseting the `f` queryParam.
=> Fix(freestyle-menu): Reset f queryParam in menu

addon/components/freestyle-collection.js
When navigating away from a style guide (especially in an automated testing context) this run.next can sometimes fire after the component is destroyed. This prevents that from happening.
=> Fix 'calling set on destroyed object' error

addon/components/freestyle-md-text.js, addon/templates/components/freestyle-notes.hbs, app/components/freestyle-md-text.js, index.js, package.json
NOTE: Currently on a fork until
https://github.com/johnotander/ember-remarkable/pull/34 is merged
This commit pulls the injection of the "hljs" class selector into a
freestyle-md-text component that extends md-text from ember-remarkable.
Prior to this, this hack had been done on an ember-remarkable fork I
was maintaining. It's nice to be rid of that bit of silliness.
=> Update to ember-remarkable 3.6.0

README.md, addon/components/freestyle-snippet.js, addon/styles/components/freestyle-palette-item.scss, blueprints/ember-freestyle/files/__root__/app/controllers/freestyle.js, freestyle-usage-snippet-finder.js, tests/dummy/app/controllers/application.js, tests/dummy/app/templates/application.hbs
This fixes up a git snafu. I could have sworn this changeset made it into v0.2.14. Anyway, better late than never.
Resolves https://github.com/chrislopresto/ember-freestyle/issues/99
=> Change to underscore delimiter for Windows-friendly snippet names

README.md, addon/components/freestyle-snippet.js, addon/components/freestyle-usage.js, addon/styles/components/freestyle-palette-item.scss, blueprints/ember-freestyle/files/__root__/app/controllers/freestyle.js, freestyle-usage-snippet-finder.js, tests/dummy/app/controllers/application.js, tests/dummy/app/templates/application.hbs, tests/integration/components/freestyle-usage/component-test.js
This entire technique is a bit of a hack. The goal here is to switch the
delimiter to something more noticeable.
=> Change snippet delimiter from `:` to `--`

README.md
emberobserver.com lists this addon as "wip":
So I removed this from the Readme, to allow having a score on emberobserver!
=> Remove wip status from README

addon/styles/components/freestyle-guide.scss
I noticed that the `FreestyleGuide-content` area of the style guide can occasionally stretch beyond the bounds of the page.
This happens especially when a component may have large amounts of text or when a `freestyle-collection` of many items is set to `inline=true`.
By setting `overflow: auto` on this selector, the child elements better observe the given space by the master detail flex relation between `FreestyleGuide-content` and its parent instead of trying to extend beyond the bounds and preventing shrink.
=> Fix horizontal scroll on content

.travis.yml, package.json, yarn.lock
Eliminates build-time warning of the form "Warning: ignoring input sourcemap for vendor/showdown.js because ENOENT: no such file or directory, open '[snip]/ember-freestyle/tmp/source_map_concat-input_base_path-[random].tmp/vendor/showdown.js.map'
=> Update ember-cli-showdown to ^3.2.1

index.js, package.json
broccoli-unwatched-tree is deprecated, replaced with the functionality of broccoli-source. Anybody who is using Ember Freestyle can't build their Ember CLI application right now because of https://github.com/rwjblue/broccoli-unwatched-tree/issues/4 -- but since broccoli-unwatched-tree is deprecated, it should be replaced by broccoli-source.
Fixes #125 
Supersedes #126
=> Replace broccoli-unwatched-tree with broccoli-source

README.md, addon/templates/components/freestyle-collection.hbs, addon/templates/components/freestyle-section.hbs, tests/dummy/app/templates/application.hbs
**THIS IS A BREAKING CHANGE.** 
This PR incorporates https://github.com/chrislopresto/ember-freestyle/pull/122 from @dajk and https://github.com/chrislopresto/ember-freestyle/pull/43 from @knownasilya 
- Updates the freestyle-section component to yield contextual freestyle-subsection components
- Updates the freestyle-collection component to yield contextual freestyle-variant components
```hbs
{{#freestyle-section as |section|}}
{{#freestyle-subsection section=section}}
{{#freestyle-collection as |collection|}}
{{#freestyle-variant colleciton=collection}}
{{!-- ... --}}
{{/freestyle-variant}}
{{/freestyle-collection}}
{{/freestyle-subsection}}
{{/freestyle-section}}
```
```hbs
{{#freestyle-section as |section|}}
{{#section.subsection}}
{{#freestyle-collection as |collection|}} …
```
=> Yielded Component API

addon/styles/components/freestyle-typeface.scss
The `freestyle-typeface` component dynamically receives its font-family and writes it as an inline style on the component element. In our case we had a specific font-family defined for all `<p>` tags, so the component's font definition would not trickle down to the `.FreestyleTypeface-previewSample` class.  Thus I have added `font-family: inherit` into that class to allow these `<p>` tags to use the components not and not a globally defined font-family.
=> Inherit font-family from component

addon/components/freestyle-subsection.js, addon/styles/components/freestyle-subsection.scss, addon/styles/components/freestyle-typeface.scss
Updated Subsection visibility behavior so that subsections no longer take up space in the DOM when they are not visible.
Previously the Subsection content would be hidden, but they would still take up space in the DOM:
With this change the Subsection elements will no longer take up space in the DOM:
=> Improve spacing for hidden subsections

addon/styles/components/freestyle-guide.scss
replaced non-existing `align-items: top;` for `align-items: center;` for the header
which makes it possible to remove `align-self: center;` from the cta
added `justify-content: space-between;` for the header to space the elements correctly
therefore `flex-grow: 1;` can be removed from the title container
=> Fixes for freestyleguide header

.travis.yml, addon/styles/components/freestyle-dynamic.scss, addon/templates/components/freestyle-dynamic-input.hbs, config/ember-try.js
This PR:
- updates Travis config to fix the build: https://github.com/travis-ci/travis-ci/issues/9024
- updates ember-try config to test against the 2.16 and 2.18 LTS Ember releases
- [fixes a CSS selector](https://github.com/suitcss/suit/blob/master/doc/naming-conventions.md)
=> Update LTS testing config

addon/services/ember-freestyle.js, app/initializers/ember-freestyle.js, freestyle-usage-snippet-finder.js, index.js, tests/dummy/app/templates/documentation.hbs
This PR:
- renames the freestyle snippets module for compatibility with [ember-code-snippet](https://github.com/ef4/ember-code-snippet)
- Renames a documentation snippet slug to avoid a build warning
=> Rename freestyle snippets module

addon/components/freestyle-dynamic-input.js
A recent change caused dynamic property input changes to no longer work, because it incorrectly used an underscored property name
=> Use correct property name

freestyle-usage-snippet-finder.js, tests/acceptance/section-rendering-test.js, tests/pages/freestyle-guide.js
Freestyle notes were broken, because I didn't realize `naiveMerge` only takes 2 arguments.
This fixes that, albeit in an ugly way (is there a better merge function we could use?)
Also adds a regression test.
=> Fix freestyle notes

addon/templates/components/freestyle-usage-controls.hbs
This causes a deprecation warning under Ember Canary without the change.
=> Fix component action syntax

CHANGELOG.md, package.json
shipjs runs `yarn test` by default before publishing. This PR changes the package.json test script to run `ember test` rather than the unused `ember try` setup that had been there.
=> chore: Change test command that runs while publishing

addon/templates/components/freestyle-snippet.hbs
When running the default generated freestyle-guide through aXe (an accessibility auditing tool used by many web tools like Chrome and ember-a11y-testing), we found that the keyboard could not focus on the scrollable region of the tool. Adding `tabindex="0"` here allows the keyboard user to focus the snippet and scroll the region.
https://dequeuniversity.com/rules/axe/3.3/scrollable-region-focusable
=> fix(accessibility): ensure freestyle-snippet content is accessible by screenreader

README.md, freestyle-usage-snippet-finder.js, package.json, tests/dummy/app/templates/acceptance.hbs, tests/integration/components/freestyle-usage/component-test.js
fix for issue #188 
kept support for curly-brackets
attempted to clean up the `componentSnippets` build by iterating through an array of `componentName` values, but the resulting code was taking longer to clean up than just adding and merging three more snippets
willing to work to clean up and DRY out the code with some guidance, just wanted to get it out there because we currently have a need for it with our ember-octane project
thanks in advance! and thanks for making this addon in the first place, it's rad
=> feat: Support Freestyle Usage|Note angle bracket component invocation 

index.js
This avoids a bug where the rewriting causes an error when run in ember-beta or newer with embroider:
```
The `yield` keyword was used incorrectly. It was used as a call expression, but its valid usages are:
- As an append statement, as in: {{yield}}
Error caused by:
|
|  {{yield this.dynamicPropertyValues}}
|
(error occurred in 'ember-freestyle/components/freestyle-dynamic/index.hbs' @ line 11 : column 0)
```
=> bug: Don't run AST transform on freestyle itself, just on it's parent app/addon

lib/ast-transform.js
- Ideally, freestyle's AST will run before the named-blocks-polyfill. If it doesn't, the syntax that it is looking for is very different. This commit addresses that. Note that formatting is lost by the named-blocks-polyfill. It would be better if the original authored formatting could be preserved.
Fixes #481
=> fix: Improve handling of hbs mangled by named-blocks-polyfill

addon/components/freestyle-guide/index.hbs, addon/components/freestyle-guide/index.js, addon/components/freestyle-menu/index.hbs, addon/components/freestyle-menu/index.js, addon/components/freestyle-section/index.hbs, addon/components/freestyle-section/index.js, addon/components/freestyle-subsection/index.hbs, addon/components/freestyle-subsection/index.js, addon/services/ember-freestyle.js, addon/styles/components/freestyle-guide.scss, tests/acceptance/collection-navigation-test.js, tests/acceptance/collection-rendering-test.js, tests/acceptance/section-navigation-test.js, tests/acceptance/section-rendering-test.js, tests/dummy/app/templates/documentation.hbs, tests/pages/freestyle-guide.js
My team has found that the all components menu isn't very performant since we have a ton of components, so we wanted a way to hide it from the user altogether. 
This PR adds flag to the freestyle service that the user can tap into and hide the `all` components menu in side nav.
=> feat: Add option to not show all in menu

package.json
The render modifiers are not found because `@ember/render-modifiers` is not listed under `dependencies`.
=> fix: @ember/render-modifiers must be a normal dependency

.npmignore
Should the following be added as well?
- `.all-contributorsrc` - Contributions can also be checked on GH
- `FREESTYLE_USAGE_API.md` - Seems like an API design file used for development
=> chore: update .npmignore file

package.json
Since @glimmer/tracking is used in the guide component, we should list it as a dep
=> fix: glimmer/tracker to the deps list since

addon/components/freestyle-variant-list/index.hbs, addon/helpers/equal.js, app/helpers/variant-eq.js
Since the project uses `ember-truth-helpers` again, seems like a good idea to use its `eq` helper instead of the custom `variant-eq` helper.
=> refactor: remove custom equal helpers

blueprints/ember-freestyle/files/__root__/app/controllers/freestyle.js, blueprints/ember-freestyle/files/__root__/app/templates/freestyle.hbs
- Makes sure the controller file does not fail prettier out of the box
- Removes the `BEGIN-FREESTYLE-USAGE` comment block as the current docs state that this functionality has been removed
- Updates the template file to use double quotes and changes `freestyle/palette.json` to `app/controllers/freestyle.js`
- I also removed some new lines in the template file to make it more consistent (let me know if this should be reverted)
Closes #525.
=> chore: clean up blueprint files

addon/components/freestyle-usage/index.js
As of Ember 3.27, dot access of computed macros (e.g. `computed.or`) triggers this deprecation error:
```
Using `computed.or` has been deprecated. Instead, import the value directly from @ember/object/computed:
import { or } from '@ember/object/computed';
```
=> Fix deprecated computed.or

addon/components/freestyle-palette-item/index.js, addon/components/freestyle-typeface/index.js, tests/dummy/app/components/x-bar/index.js
The previous import [is deprecated](https://deprecations.emberjs.com/v3.x#toc_ember-string-htmlsafe-ishtmlsafe) starting with Ember 3.25.
=> fix: Import htmlSafe from @ember/template

.github/workflows/ci.yml, tests/dummy/app/controllers/acceptance.js
Should hopefully get CI passing again (`ember-beta` and `ember-canary` scenario's excluded for now).
=> Don't use `computed` for two-way bound properties

package.json
Doesn't seem to be used anymore.
=> Remove `glob` as a dependency

package.json
As it's used within the `addon` folder.
=> Move `@glimmer/component` to dependencies

package.json, tests/integration/components/freestyle-palette-item/component-test.js
Most helpers from `ember-native-dom-helpers` are part of `@ember/test-helpers` which is included in the default blueprint, but for the one test where we were using `ember-native-dom-helpers` we can simply use `qunit-dom` as well.
=> Remove usage of `ember-native-dom-helpers`

lib/ast-transform.js
Using a class was deprecated in [v3.27](https://github.com/emberjs/ember.js/blob/master/CHANGELOG.md#v3270-may-3-2021).
Related PR: https://github.com/emberjs/ember.js/pull/19429.
=> Make AST plugin functional

ember-cli-build.js
`ember-native-dom-event-dispatcher` isn't a dependency anymore, so seems safe to remove this check.
=> Remove `ember-native-dom-event-dispatcher` check

addon/components/freestyle-showdown-content/index.js
The `since` and `until` values are still TBD.
Closes #608.
=> Deprecate `<FreestyleShowdownContent />` component

.github/workflows/ci.yml, addon/components/freestyle/usage/object/control/index.hbs, addon/components/freestyle/usage/object/control/index.js, addon/styles/components/freestyle/usage.scss, config/ember-try.js, package.json, tests/integration/components/freestyle/usage/object-test.js, yarn.lock
`ember-json-viewer` is still required to offer support for Ember v2.12.
We've tried updating the addon to provide support for Ember v4 while
still maintaining support for v2.12, but this wasn't very straight forward.
For the time being, it's easier to just drop `ember-json-viewer` as a dependency
and use an alternative instead, being `json-formatter-js`.
Closes #595.
=> Remove `ember-json-viewer`

package.json, yarn.lock
Unpins `socket.io` again as https://github.com/socketio/socket.io/issues/4121 has been resolved and released.
=> Unpin `socket.io`

addon/components/freestyle/usage/array/index.hbs, addon/components/freestyle/usage/bool/index.hbs, addon/components/freestyle/usage/number/index.hbs, addon/components/freestyle/usage/object/index.hbs, addon/components/freestyle/usage/string/index.hbs, tests/integration/components/freestyle/usage/string-test.js
Prevents controls from being rendered despite `@hideControls` being set to `true`.
=> fix: pass down @hideControls argument

addon/modifiers/freestyle-highlight.js, package.json, yarn.lock
New deprecations were introduced in `ember-modifier` v3.2.
The migration guide can be found [here](https://github.com/ember-modifier/ember-modifier/blob/master/MIGRATIONS.md).
=> Resolve `ember-modifier` deprecations

addon/components/freestyle-menu/index.hbs
I noticed for submenus, we were rendering a `ul` tag _per_ submenu link:
If I'm not mistaken, there should be only one `ul` tag for a submenu, but including multiple `li` tags.
This PR should fix that.
NOTE: It's easier to review without whitespace changes.
=> Fix rendering too many submenus

addon/components/freestyle-guide/index.hbs, addon/components/freestyle-section/index.hbs, addon/components/freestyle-subsection/index.hbs
Currently the addon renders a bunch of divs instead of heading tags.
This is an accessibility issue.
Also I think it could be a good idea to render links with anchor inside each title. What do think?
=> Render headings instead of divs

app/styles/components/freestyle-guide.scss, vendor/ember-freestyle.css
Style-guide pages can get pretty long (specially in the `All` view). Making the navigation menu sticky avoids the user having to scroll back up when they want to navigate to a different section.
Related to #848.
Result:
https://user-images.githubusercontent.com/7403183/192954222-8e0ff202-1465-4769-be3c-84dc43c14dfb.mov
=> Make the navigation menu sticky

.github/workflows/ci.yml, index.js, package.json, yarn.lock
Fix based on the code example shown [here](https://github.com/ember-cli/ember-cli-preprocess-registry#addon-usage).
Closes #927.
=> Fix compatibility with `ember-cli` v5

addon/components/freestyle/usage/component-like/control/index.hbs, addon/components/freestyle/usage/component-like/control/index.ts, addon/components/freestyle/usage/component-like/index.hbs, addon/components/freestyle/usage/component-like/index.ts, addon/components/freestyle/usage/index.hbs, addon/components/freestyle/usage/index.ts, addon/glint.ts, app/components/freestyle/usage/component-like.js, app/components/freestyle/usage/component-like/control.js, package.json, tests/dummy/app/components/markdown-content/index.ts, tests/integration/components/freestyle/usage/component-like-test.ts, yarn.lock
e.g.
```hbs
<:api as |Args|>
<Args.Component
@name='icon'
@description='Icon component reference'
@value={{this.icon}}
@options={{array IconPlusCircle IconMinusCircle IconPencil}}
@onInput={{fn (mut this.icon)}}
/>
...
</:api>
```
=> Add an Api type to Freestyle::Usage for when you expect a component as argument

package.json
At the moment, we use `@ember/string` without declaring it as a peer dependency.
This breaks in Ember v5 as `@ember/string` has been removed from `ember-source`.
This signals to users that they need to install `@ember/string` themselves.
This is the same as how `ember-data` and other addons do it, making sure only one copy of `@ember/string` is installed (the one by the app).
=> Add `@ember/string` as a peer dependency

package.json, pnpm-lock.yaml
Now when including ember-freestyle as well as tracked-built-ins directly, the dependency version mismatch.
The major change in tracked-built-ins v4 is that the minimum typescript version is upgraded, but ember-freestyle satisfies this version requirement.
=> fix: allow new major version of tracked-built-ins
